# Generated by Django 5.0.2 on 2024-02-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_info_cmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=50, null=True)),
                ('CompanyName', models.CharField(max_length=50, null=True)),
                ('reg_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('mobile1', models.CharField(max_length=50, null=True)),
                ('mobile2', models.CharField(max_length=50, null=True)),
                ('email1', models.EmailField(max_length=254, null=True)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('date_incorporation', models.DateField(null=True)),
                ('roc', models.CharField(max_length=50, null=True)),
                ('gstin', models.CharField(max_length=50, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('class_company', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('activity', models.CharField(max_length=50, null=True)),
                ('age_company', models.CharField(max_length=50, null=True)),
                ('total_members', models.IntegerField(null=True)),
                ('logo', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
