# Generated by Django 5.0.2 on 2024-02-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_basic_info_cmp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='basic_info_cmp',
            new_name='tbl_basic_info_cmp',
        ),
    ]
