# Generated by Django 5.0.2 on 2024-02-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_tbl_basic_info_cmp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_basic_info_cmp',
            name='activity',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
