# Generated by Django 5.0.2 on 2024-02-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_tbl_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=100, null=True)),
                ('director_designation', models.CharField(max_length=100, null=True)),
                ('director_address', models.CharField(max_length=255, null=True)),
                ('director_email', models.CharField(max_length=100, null=True)),
                ('director_pan', models.CharField(max_length=120, null=True)),
                ('director_aadhaar', models.CharField(max_length=250, null=True)),
                ('director_din', models.CharField(max_length=255, null=True)),
                ('director_phone', models.CharField(max_length=20, null=True)),
                ('director_father_name', models.CharField(max_length=100, null=True)),
                ('director_status', models.BooleanField(null=True)),
                ('director_dob', models.DateField(blank=True, null=True)),
                ('director_photo', models.CharField(blank=True, max_length=200, null=True)),
                ('director_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
